name: Update Fire Rating

on:
  schedule:
    - cron: '0 21 * * *'  # Runs every day at 7am AEST (21:00 UTC)
  workflow_dispatch:      # Allows manual trigger

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 18

    - name: Install dependencies
      run: npm install xml2js node-fetch

    - name: Run script
      run: node update-fire-ratings.js

    - name: Commit and push changes
      run: |
        git config user.name "github-actions"
        git config user.email "github-actions@github.com"
        git add fire-rating.json
        git commit -m "Update fire rating"
        git push
